-- 集采日金额统计台账 建表脚本
-- 目标库：scm_source_test（生产上线时改为 scm_source）
CREATE TABLE IF NOT EXISTS `sc_collection_daily_amount_ledger` (
  `ledger_id` varchar(32) NOT NULL COMMENT '主键id',
  `ledger_no` varchar(32) DEFAULT NULL COMMENT '集采日金额统计流水号 JCRJE-yyyyMMdd-NNN',
  `execute_unit_id` varchar(32) DEFAULT NULL COMMENT '集采执行单位id',
  `execute_unit_code` varchar(64) DEFAULT NULL COMMENT '集采执行单位编码',
  `execute_unit_name` varchar(200) DEFAULT NULL COMMENT '集采执行单位名称',
  `category_code` varchar(32) DEFAULT NULL COMMENT '集采类目编码',
  `category_name` varchar(128) DEFAULT NULL COMMENT '集采类目名称',
  `statistic_date` date DEFAULT NULL COMMENT '统计日期',
  `purchase_company_id` varchar(32) DEFAULT NULL COMMENT '采购企业id',
  `purchase_company_code` varchar(64) DEFAULT NULL COMMENT '采购企业编码',
  `purchase_company_name` varchar(200) DEFAULT NULL COMMENT '采购企业名称',
  `tax_amount` decimal(20,2) DEFAULT NULL COMMENT '交易金额(含税/元)',
  `bu_code` varchar(32) DEFAULT NULL COMMENT '所属板块编码',
  `bu_name` varchar(64) DEFAULT NULL COMMENT '所属板块名称',
  `publish_time` datetime DEFAULT NULL COMMENT '最新发布/修改时间',
  `publish_by` varchar(32) DEFAULT NULL COMMENT '最新发布/修改人id',
  `publish_by_name` varchar(64) DEFAULT NULL COMMENT '最新发布/修改人',
  `create_by` varchar(32) DEFAULT NULL COMMENT '创建人ID',
  `create_by_name` varchar(32) DEFAULT NULL COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_by` varchar(32) DEFAULT NULL COMMENT '更新人ID',
  `update_by_name` varchar(32) DEFAULT NULL COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `delete_sign` int(11) DEFAULT '0' COMMENT '删除标记 0正常 1删除',
  PRIMARY KEY (`ledger_id`) USING BTREE,
  UNIQUE KEY `uk_ledger_no` (`ledger_no`) USING BTREE,
  KEY `idx_statistic_date` (`statistic_date`) USING BTREE,
  KEY `idx_execute_unit` (`execute_unit_code`) USING BTREE,
  KEY `idx_purchase_company` (`purchase_company_code`) USING BTREE,
  KEY `idx_category` (`category_code`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC COMMENT='集采日金额统计台账';
